### ISSUE TITLE
Create intercept.js

### ISSUE THREAD

**Issue by jamesplease** [jmeas/backbone.intercept#11]
This library doesn't need to have a BB dep. I should take the meat of its logic out and place it into intercept.js, which provides a callback once something is intercepted. At that point, I could make bb.intercept _on top_ of that.

**Comment by stephanebachelier** [comment]
@jmeas will you create a separate repo for intercept.js ?

**Comment by jmeas** [comment]
If I ever get around to splitting it out, then yeah, that would be the plan. It would just be 'bundled' up with bb.intercept so to the end-user there would be no difference.
