### ISSUE TITLE
Add docs about how to cancel routing

### ISSUE THREAD

**Issue by jmeas** [jmeas/backbone.intercept#19]
The answer: handle that in your router. This library is only meant to act as a proxy between the DOM and your JS, and nothing more.

**Comment by thejameskyle** [comment]
This doesn't seem necessary to document.

**Comment by jmeas** [comment]
Someone mentioned it as a reason to consider not using this library, so I want to make it explicitly clear that it isn't a responsibility of this lib.

**Comment by thejameskyle** [comment]
You don't see the price of tea in China documented here either :stuck_out_tongue_winking_eye:

**Comment by jmeas** [comment]
lol : [
