### ISSUE TITLE
link parameters omission

### ISSUE THREAD

**Issue by elgubenis** [jmeas/backbone.intercept#21]
hey, i like bb.intercept, i just have one question,
i have a link tag which uses 'example.com/a?page=1' as a href,
when i start bb.intercept and click the link, i get navigated to: 'example.com/a' is there a way  to get navigated to the whole uri?

**Comment by jmeas** [comment]
I'll look into this. It might be a bug. Thanks @elgubenis !

**Comment by jmeas** [comment]
Resolved in #22
