### ISSUE TITLE
Upgrade Backbone dependency to 1.2.1

### ISSUE THREAD

**Issue by jeffijoe** [jmeas/backbone.intercept#26]
I am using Webpack, and `require` behavior dictates that if a version mismatch is found, both modules are imported.

This poses a problem since Backbone uses a singleton `History` object to track `started` state. This results in 2 instances of the History singleton existing, because 2 different Backbone modules are being pulled in.

I'd do this myself but since I am on Windows the Contextify dependency won't install, and so I can't run the magical tests.

**Comment by jmeas** [comment]
PRs welcome!

**Comment by jeffijoe** [comment]
@jmeas already did, need the stamp of pls :D

**Comment by jmeas** [comment]
Oh weird, Github didn't send me a notification for the PR. My mistake!

**Comment by jmeas** [comment]
Released as 0.4.0.

**Comment by elgubenis** [comment]
the same now for 1.2.3 with browserify, backbone gets included 2 times in 1 bundle once with version 1.2.1 (from intercept) and ther other 1.2.3

**Comment by jmeas** [comment]
Thanks for the PR to fix this, @elgubenis ! It's released on Bower and npm as 0.4.1.
